# Generated by Django 4.2.6 on 2024-03-09 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artistmodule', '0002_artistdetails_song_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistdetails',
            name='artist_name',
            field=models.CharField(default='Unknown Artist', max_length=100),
        ),
    ]
